Handle image name with special char
shamedgh/confine pull request #4
Opened 2021-10-25 11:10 UTC by chethanah

Hello @shamedgh,

**Problem Statement**
- Sometimes required to harden container images of specific tag.
- When image name is mentioned with tag name in input image json file, the `output//<imagename>` is created. In that case Confine fails to harden container image, since unable to read any binaries or libraries from  `output//<imagename>` .
- Consider the following example
```
$ cat image.json 
{
    "nginx": {
        "enable": "true",
        "image-name": "nginx:1.21.3",
        "image-url": "nginx:1.21.3",
        "options": "",
        "args": ""
    }
}
```
- Run confine to harden `"nginx:1.21.3"` image
```
$ sudo python3.8 confine.py -d -l libc-callgraphs/glibc.2.31.callgraph -m libc-callgraphs/musllibc.callgraph -i image.json -o output/ -p default.seccomp.json -r results/ -g go.syscalls/ --finegrain --othercfgfolder other-callgraphs/ 2>&1 | tee confinerun-master-imagename.log 
...<SKIP>...
Successfully created directory: output//nginx:1.21.3/
...<SKIP>...
Finished sleeping, extracting psNames for nginx:1.21.3
Starting to identify running processes and required binaries and libraries through dynamic analysis.

nginx:1.21.3 container can't be hardened because no functions can be extracted from binaries and no direct syscalls found
Tried hardening container: nginx:1.21.3 returned: -3:No imported functions could be extracted from any of the binaries and libraries required by the container
```
- Log: 
[confinerun-master-imagename.log](https://github.com/shamedgh/confine/files/7409463/confinerun-master-imagename.log)

**Changes**
- Convert any special characters in `image-name` to only alpha-num value
- This updates the imagename 
- Example: `"image-name": "nginx:1.21.3"` -> `output/nginx1213`
- Using above `image.json`
```
$ sudo rm -rf output/ results/
$ sudo python3.8 confine.py -d -l libc-callgraphs/glibc.2.31.callgraph -m libc-callgraphs/musllibc.callgraph -i image.json -o output/ -p default.seccomp.json -r results/ -g go.syscalls/ --finegrain --othercfgfolder other-callgraphs/ 2>&1 | tee confinerun-handle-ouputdir-imagename.log 
...<SKIP>...
Successfully created directory: output//nginx1213/
...<SKIP>...
--->Validating generated Seccomp profile: results//nginx1213.seccomp.json
Running container nginx
docker inspect status returned: true

************************************************************************************
Finished validation. Container for image: nginx1213 was hardened SUCCESSFULLY!
************************************************************************************
```
- Log: 
[confinerun-handle-ouputdir-imagename-1.log](https://github.com/shamedgh/confine/files/7409521/confinerun-handle-ouputdir-imagename-1.log)

2021-11-17 05:42 UTC, chethanah commented
Hello @shamedgh , kindly review these changes. Please feedback if any comments.

2021-11-17 15:28 UTC, shamedgh requested changes
Thanks for the change!
Could we replace the problematic characters with a dash?
Instead of:
`re.sub('\W+','', tmpimageName)`
Can we do:
`re.sub('\W+','-', tmpimageName)`

For large image names like `store/oracle/database-enterprise:12.2.0.1` it will have a more user-friendly output.

2021-11-29 17:41 UTC, chethanah commented
Hello @shamedgh, I updated the required changes `e.sub('\W+','-', tmpimageName)`. 
Kindly review and merge if no feedback.

2021-11-29 18:02 UTC, shamedgh approved these changes

2021-11-29 18:02 UTC, merged